
---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "goliatdashboard_organization Resource - goliatdashboard Provider"
subcategory: ""
description: |-
  The `goliatdashboard_organization` resource allows you to manage organizations in the Goliat Dashboard.
---

# goliatdashboard_organization (Resource)

The `goliatdashboard_organization` resource allows you to create, read, update, and delete organizations in the Goliat Dashboard.

## Example Usage

```terraform
provider "goliatdashboard" {
  backend_url = "http://localhost:4321"
  token       = "123"
}

resource "goliatdashboard_organization" "example" {
  name = "New Provider Organization"
  type = "providerOrganizations"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `name` (String) - The name of the organization.
- `type` (String) - The type of the organization.

### Read-Only

- `id` (String) - The ID of the organization, assigned by the API upon creation.
